---
- hosts: all

  tasks:
   - name: check if epel is on server
     stat: path=~/epel-release-7-7.noarch.rpm
     register: epel

   - name: add repository
     shell: "wget -nc https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm && rpm -ivh epel-release-7-7.noarch.rpm"
     when: epel.stat.exists != True

   - name: install prereqs 
     yum: pkg=nodejs,npm,ruby,ruby-devel state=installed update_cache=true

   - name: install jekyll
     shell: "sudo gem install jekyll"

   - name: build jekyll
     shell: "cd {{ docroot }}/jekyll && jekyll build"
